version: "3"

services:
  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
      - gcp-status
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.enable-lifecycle
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/rules.yml:/etc/alertmanager/rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - ${PWD}/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093

  gcp-status:
    image: ghcr.io/dazwilkin/gcp-status:641b5c42275df15e8072c2e6c5885e667ec57416
    container_name: gcp-status
    expose:
      - "9989"
    ports:
      - 9989:9989
