version: "3"

services:
  gcp-status:
    image: ghcr.io/dazwilkin/gcp-status:be5308701567385d30ec6d57b54da1dd7b94cd1c
    container_name: gcp-status
    expose:
      - "8080"
    ports:
      - 8080:8080
