version: "3"

services:
  gcp-status:
    image: ghcr.io/dazwilkin/gcp-status:49ae01e1c02e138033fb9d5a0c938b642889dc24
    container_name: gcp-status
    expose:
      - "8080"
    ports:
      - 8080:8080
