apiVersion: v1
kind: List
metadata: {}
items:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: gcp-status
      name: gcp-status
    spec:
      selector:
        app: gcp-status
      ports:
        - name: metrics
          port: 9989
          targetPort: 9989
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: gcp-status
      name: gcp-status
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: gcp-status
      template:
        metadata:
          labels:
            app: gcp-status
        spec:
          containers:
            - name: gcp-status
              image: ghcr.io/dazwilkin/gcp-status:ae3fc74f3245a46d984c040b863e2a2980ff3ce2
              ports:
                - name: metrics
                  containerPort: 9989
          restartPolicy: Always
  - kind: ServiceMonitor
    apiVersion: monitoring.coreos.com/v1
    metadata:
      name: gcp-status
      labels:
        app: gcp-status
    spec:
      selector:
        matchLabels:
          app: gcp-status
      endpoints:
        - port: metrics
